// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvbTIhII6vzHdEZ7_JfyLnzbwqVMYLYKo',
    appId: '1:611143451260:web:b96f51068e868371017ff9',
    messagingSenderId: '611143451260',
    projectId: 'my-note-f3101',
    authDomain: 'my-note-f3101.firebaseapp.com',
    storageBucket: 'my-note-f3101.appspot.com',
    measurementId: 'G-HZPRT9E9FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCylqRMXhOyPBnRNV8JeX8J4kv4HQ98TdM',
    appId: '1:611143451260:android:dfd7f81f8c954316017ff9',
    messagingSenderId: '611143451260',
    projectId: 'my-note-f3101',
    storageBucket: 'my-note-f3101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDxRC_6JGBFXl27yG9XMoB_E4Zm5-wtAE',
    appId: '1:611143451260:ios:2ef3f9c74b32610e017ff9',
    messagingSenderId: '611143451260',
    projectId: 'my-note-f3101',
    storageBucket: 'my-note-f3101.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDxRC_6JGBFXl27yG9XMoB_E4Zm5-wtAE',
    appId: '1:611143451260:ios:42ffe4fde4f60120017ff9',
    messagingSenderId: '611143451260',
    projectId: 'my-note-f3101',
    storageBucket: 'my-note-f3101.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
